apiVersion: integration.ibm.com/v1beta1
kind: Demo
metadata:
  name: demo-setup
  namespace: cp4i
spec:
  addons:
    elasticSearch: false
    ocpPipelines: true
    postgres: true
  demos:
    cognitiveCarRepair: false
    drivewayDentDeletion: true
    eventEnabledInsurance: false
    mappingAssist: false
    weatherChatbot: false
  general:
    storage:
      block:
        class: ocs-storagecluster-ceph-rbd
      file:
        class: ocs-storagecluster-cephfs
  license:
    accept: true
    ace: L-APEH-C49KZH
    demo: L-RJON-BYRMYW
    apic: L-RJON-BRSHKF
    ar: L-NCAN-BXWG76
    mq: L-RJON-BQPGWD
    tracing: L-RJON-BQPGWD
  products:
    aceDashboard: true
    aceDesigner: true
    apic: false
    assetRepo: false
    eventStreams: false
    mq: true
    tracing: true
  version: 2021.3.1
